var playlist = [
{"title":"Majestic Blues","url":"http://pjslack.net/majesticblues2.mp3"},
{"title":"Freedom Calls your NAme","url":"http://pjslack.net/freedomcallsyourname.mp3"},
{"title":"Em Umna Outra Vida","url":"http://pjslack.net/emumaoutravida.mp3"},
{"title":"Cupid's Arror 2","url":"http://pjslack.net/cupidsarrow2.mp3"},
{"title":"Cup Half Empty","url":"http://pjslack.net/cuphalfempty.mp3"},
{"title":"Never Lost","url":"http://pjslack.net/neverlost.mp3"},
{"title":"Forever Just A Step Away","url":"http://pjslack.net/forever.mp3"},
{"title":"Raccoon Requiem","url":"http://pjslack.net/raccoons.mp3"},
{"title":"Gerogian Waves","url":"http://pjslack.net/georgianwaves.mp3"},
{"title":"Multiverse","url":"http://pjslack.net/multiverse.mp3"},
{"title":"Light Fantastica","url":"http://pjslack.net/lightfantastica.mp3"},
{"title":"Oasis Tango","url":"http://pjslack.net/oasistango-mastered.mp3"},
{"title":"Destination Unkown","url":"http://pjslack.net/destinationunknown.mp3"},
{"title":"LowVille","url":"http://pjslack.net/lowville.mp3"},
{"title":"","url":"http://pjslack.net/wbblues.mp3"},
{"title":"Waltz of the Empaths","url":"http://pjslack.net/waltzoftheempath.mp3"},
{"title":"Loss For Words","url":"http://pjslack.net/lossforwords.mp3"},
{"title":"It's Raining","url":"http://pjslack.net/itsraining.mp3"},
{"title":"Brown Jug Separation","url":"http://pjslack.net/brownjug.mp3"},
{"title":"I'll See You In The Morning","url":"http://pjslack.net/seeyouinthemorning.mp3"},
{"title":"Island River Heart","url":"http://pjslack.net/islandriverheart.mp3"},
{"title":"Iceberg","url":"http://pjslack.net/iceberg.mp3"},
{"title":"Just to Brighten Up Your Day","url":"http://pjslack.net/jtbyd.mp3"},
{"title":"Heal The Children","url":"http://pjslack.net/healthechildren.mp3"},
{"title":"Take the Ride","url":"http://pjslack.net/taketheride.mp3"},
{"title":"????","url":"http://pjslack.net/track5-m.mp3"},
{"title":"Sand Castles","url":"http://pjslack.net/sandcastles.mp3"},
{"title":"Deep Inside","url":"http://pjslack.net/deepinside.mp3"},
{"title":"Sagitarian Healers","url":"http://pjslack.net/chantforsagitarianhealers.mp3"},
{"title":"Eyes of Jupiter","url":"http://pjslack.net/eyesofjupiter.mp3"},
{"title":"For My Own","url":"http://pjslack.net/myown.mp3"},
{"title":"Love Walks In","url":"http://pjslack.net/lovewalksin.mp3"},
{"title":"Guardian Angel","url":"http://pjslack.net/guardianangel02.mp3"},
{"title":"Cosimc Rift","url":"http://pjslack.net/cosmicrift.mp3"},
{"title":"North American Dream","url":"http://pjslack.net/nadream.mp3"},
{"title":"Silence Spoken","url":"http://pjslack.net/silencespoken.mp3"},
{"title":"Drift Away","url":"http://pjslack.net/driftaway-1.mp3"},
{"title":"Colours of Your Heart","url":"http://pjslack.net/colours.mp3"},
{"title":"Cats on Venus","url":"http://pjslack.net/catsonvenus.mp3"},
{"title":"Man on a String","url":"http://pjslack.net/manonastring.mp3"},
{"title":"cupids arrow 2","url":"http://pjslack.net/cupidsarrow2-ccpub.mp3"},
{"title":"In My Favourite Book","url":"http://pjslack.net/inmyfavouritebook.mp3"},
{"title":"On The Farm","url":"http://pjslack.net/onthefarm.mp3"},
{"title":"GENX","url":"http://pjslack.net/cataclysm/genx.mp3"},
{"title":"Cupid's Arrow","url":"http://pjslack.net/cataclysm/cupidsarrow.mp3"},
{"title":"Almost","url":"http://pjslack.net/cataclysm/almost.mp3"},
{"title":"","url":"http://pjslack.net/cataclysm/awave.mp3"},
{"title":"Cameron","url":"http://pjslack.net/cataclysm/cameron.mp3"},
{"title":"Falling Over","url":"http://pjslack.net/cataclysm/fallingover.mp3"},
{"title":"When I'm With You","url":"http://pjslack.net/whenimwithyou.mp3"},
{"title":"Gringo-a-Gringo","url":"http://pjslack.net/gringoagringo.mp3"},
{"title":"Let The Sun Shine","url":"http://pjslack.net/letthesunshine.mp3"},
{"title":"Seven Rings of Saturnalia","url":"http://pjslack.net/saturn-1.mp3"},
{"title":"Live on Erin Radio","url":"http://pjslack.net/peterslackshow.mp3"},
{"title":"NorthBound","url":"http://pjslack.net/Northbound-new.mp3"},
{"title":"Falling Over","url":"http://pjslack.net/fallingover.mp3"},
{"title":"Island River Heart","url":"http://pjslack.net/islandriverheart-mixed.mp3"},
{"title":"Declassified","url":"http://pjslack.net/declassified.mp3"},
{"title":"Life's Waltz","url":"http://pjslack.net/lifeswaltz.mp3"},
{"title":"Rat Race","url":"http://pjslack.net/ratrace.mp3"},
{"title":"Bed of Northern Lights","url":"http://pjslack.net/BedofNorthernLights.mp3"},
{"title":"Silence and Symmetry","url":"http://pjslack.net/silenceandsymmetry.mp3"},
{"title":"Slow Dancing","url":"http://pjslack.net/slowdancing.mp3"},
{"title":"Daddies out Working","url":"http://pjslack.net/goldminefinalmix2oct18.mp3"},
{"title":"Mother's going to Melt Your Ice","url":"http://pjslack.net/mothersgoingtomeltyourice.mp3"},
{"title":"The Value Of A Man","url":"http://pjslack.net/thevalueofaman.mp3"},
{"title":"Life Does Sing","url":"http://pjslack.net/lifedoessing.mp3"}
];
